### ISSUE TITLE
Environment specific CONFIGfile

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ApplicationPattern#250]
The CONFIGfile contains all data that is necessary to establish the connections, which are required for properly operating the application.
TCP/IP addresses, operation names and application release number might depend on the environment (e.g. SDN test laboratory or live network) in which the application gets instantiated in.
As a consequence the CONFIGfile has to be adapted to the environment before instantiation.
This adaption shall be automated.

This issue shall subsume all the necessary steps (and reference the corresponding issues) for automating adaption of the CONFIGfile:
- [ ] The concept of the fake IP addresses has to be mentioned in [Concept of the ServiceList](../blob/develop/doc/SpecifyingApplications/ConceptOfServiceList/ConceptOfServiceList.md) (#242)
- [ ] The [Creating the ServiceList](../blob/develop/doc/SpecifyingApplications/CreatingServiceList/CreatingServiceList.md) has to be double checked for requesting for adding fake IP addresses (#243)
- [x] A [list of fake IP addresses](../blob/develop/doc/TestingApplications/Infrastructure/SdnLaboratory/IpAddresses/IpAddresses.md) has to be created and to be maintained.
- [ ] The [Concept of CONFIGfile](../blob/develop/doc/SpecifyingApplications/LoadFile/LoadFile.md) has also to mention the concept of the fake IP addresses and to request for properly transferring the values according to the [list of fake IP addresses](../blob/develop/doc/TestingApplications/Infrastructure/SdnLaboratory/IpAddresses/IpAddresses.md) (#244)
- [ ] List for translating fake IP addresses into the TCP/IP addresses of the SDN laboratory to be created and to be maintained (#245).
- [ ] List for translating fake IP addresses into the TCP/IP addresses of the live network to be created and to be maintained (#246).
- [ ] A script has to be written for translating fake IP addresses into the TCP/IP addresses according to the respective environment (#247).
- [ ] Testing guidelines shall be complemented by guideline about how to apply the script (#248).
- [ ] Deployment guidelines shall be complemented by guideline about how to apply the script (#249).

**Comment by sunil-kumar-meena** [comment]
“As decided in this issue , https://github.com/openBackhaul/ApplicationPattern/issues/247 ,
We are not supporting replacing the release-numbers.
Also , instead of replacing the fake-ips with the original-ips , we are using the application-name and release-number as a key to update the original IPs in the config file.
Required code changes for updating the original IPs are delivered as a part of this PR https://github.com/openBackhaul/ApplicationPattern/pull/706.
So , closing this issue.”
